postgis:
  image: mdillon/postgis

mongo:
  image: mongo

rabbitmq:
  image: rabbitmq

memcached:
  image: memcached

kobocat:
  build: .
  command: /bin/bash run.sh
  ports:
    - "8000:8000"
  links:
    - postgis
    - mongo
    - rabbitmq
    - memcached
